apiVersion: v1
kind: Secret
metadata:
  name: rh-ee-sampark-nfs-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbWd0WldVdGMyRnRjR0Z5YXl0dVpuTTZXVVk1U1VoRFVsaE1Tek5ITVVKVE5VSkxWMVpIV2prM1JGQXhVVVZMTURkUFJVSkhRelZMTlRoQlNrRlVVbGRYTkZkU1dUSkpXREF5VmpKU09GaFpOdz09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson