apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-eco-storage-<username>
  namespace: <username>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: gp3-csi
