apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-storage
  namespace: <username>
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ibmc-vpc-file-metro-retain-1000-iops
  resources:
    requests:
      sotrage: 250Gi