apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backing-storage
  namespace: nfs-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-nvme-vg
  resources:
    requests:
      storage: 3Ti