apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-eco-storage-<username>
  namespace: <username>
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ocs-storagecluster-cephfs
