apiVersion: v1
kind: Secret
metadata:
  name: rh-ee-sampark-dev-bot-pull-secret
  namespace: <username>
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvL3JoLWVlLXNhbXBhcmsiOiB7CiAgICAgICJhdXRoIjogImNtZ3RaV1V0YzJGdGNHRnlheXRrWlhaZlltOTBPa1JZV0ZKWE5rY3hSazFLUzB4RVNWaEpXRU5HTURWQ1FVUXdVRUV3VUVsTlFqZFBObFpIVmxVek1qTXhPVmRYU0U0MU1UVkVTVkpGVTFveFN6a3lTakU9IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson